spring:
  jpa:
    database: mysql
  datasource:
    password: vnkskw3oifdocpvkakwnfnc242jsn
    driver-class-name: com.postgresql.cj.jdbc.Driver
    username: postgres
    url: postgresql://edevdatabase.cnpnvogpabsr.ap-northeast-2.rds.amazonaws.com:5432/devewha
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher